server:
  port: 8081
  tomcat:
    max-connections: 200
    max-threads: 200
    connection-timeout: 30000
  servlet:
    context-path: /api
    context-parameters:
      socket-timeout: 30000

spring:
  serverHost: 192.168.1.122
  serverPort: 27017
  userName: master
  passWord: master
  authDB: admin
  data:
    mongodb:
      database: brain_db_dev
      uri: mongodb://${spring.userName}:${spring.passWord}@${spring.serverHost}:${spring.serverPort}/${spring.data.mongodb.database}?authSource=${spring.authDB}
  servlet:
      multipart:
          enabled: true
          max-file-size: 512MB
          max-request-size: 512MB
  mvc:
    async:
      request-timeout: 60000